### ISSUE TITLE
Broaden time step considerations to include models that other than annually

### ISSUE THREAD

**Issue by amandadsmith** [IMMM-SFA/im3py#6]
Generalize the requirements for time steps so that models running time steps other than yearly time steps can be exposed at the correct interval to interact with other models.

Broaden the time-step requirement to encompass sub-annual (or multi-annual, perhaps) steps in individual models.

Be careful with time step language as this may mean different things to different modelers.

BEND notes:
- BEND runs sub-annually
 - Simulation time step is generally ~10 min
 - Standard simulation output is hourly

Note from @crvernon : We should probably let BEND just create its native outputs in 1 hour and then let what ever model that receives those outputs aggregate them as need be. This is what we do with MOSART-WM.

See related: https://im3-sfa.slack.com/archives/CREHFTAJ2/p1586798306000100?thread_ts=1586551074.016600&cid=CREHFTAJ2

**Comment by crvernon** [comment]
Addressed in PR #9
